# Form implementation generated from reading ui file 'D:\duanmonhoc\ui\QuanLySach.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1574, 993)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(208, 216, 224);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font: 75 26pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(40,103,129);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBoxCo = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxCo.sizePolicy().hasHeightForWidth())
        self.groupBoxCo.setSizePolicy(sizePolicy)
        self.groupBoxCo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBoxCo.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"color: rgb(0, 51, 102);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.groupBoxCo.setObjectName("groupBoxCo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxCo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBoxCo)
        self.tableWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.tableWidget.setStyleSheet("background-color: rgb(40,103,129);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(235)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.verticalHeader().setDefaultSectionSize(60)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditBookName = QtWidgets.QLineEdit(parent=self.groupBoxCo)
        self.lineEditBookName.setObjectName("lineEditBookName")
        self.gridLayout.addWidget(self.lineEditBookName, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBoxCo)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBoxCo)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEditISBN = QtWidgets.QLineEdit(parent=self.groupBoxCo)
        self.lineEditISBN.setObjectName("lineEditISBN")
        self.gridLayout.addWidget(self.lineEditISBN, 0, 1, 1, 1)
        self.lineEditQuantity = QtWidgets.QLineEdit(parent=self.groupBoxCo)
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.gridLayout.addWidget(self.lineEditQuantity, 4, 1, 1, 1)
        self.lineEditPubYear = QtWidgets.QLineEdit(parent=self.groupBoxCo)
        self.lineEditPubYear.setObjectName("lineEditPubYear")
        self.gridLayout.addWidget(self.lineEditPubYear, 3, 1, 1, 1)
        self.lineEditAuthor = QtWidgets.QLineEdit(parent=self.groupBoxCo)
        self.lineEditAuthor.setObjectName("lineEditAuthor")
        self.gridLayout.addWidget(self.lineEditAuthor, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.groupBoxCo)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.groupBoxCo)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBoxCo)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonThemSach = QtWidgets.QPushButton(parent=self.groupBoxCo)
        self.pushButtonThemSach.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 2px solid #0077b6; \n"
"    border-radius: 8px; \n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu xám nhạt khi hover */\n"
"    border: 2px solid #005f8a; /* Viền đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Màu nhấn */\n"
"    border: 2px solid #004a6d; \n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../images/IC_selected.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonThemSach.setIcon(icon)
        self.pushButtonThemSach.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonThemSach.setObjectName("pushButtonThemSach")
        self.gridLayout_2.addWidget(self.pushButtonThemSach, 0, 0, 1, 1)
        self.pushButtonUpdate = QtWidgets.QPushButton(parent=self.groupBoxCo)
        self.pushButtonUpdate.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 2px solid #0077b6; \n"
"    border-radius: 8px; \n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu xám nhạt khi hover */\n"
"    border: 2px solid #005f8a; /* Viền đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Màu nhấn */\n"
"    border: 2px solid #004a6d; \n"
"}\n"
"")
        self.pushButtonUpdate.setIcon(icon)
        self.pushButtonUpdate.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.gridLayout_2.addWidget(self.pushButtonUpdate, 0, 1, 1, 1)
        self.pushButtonXoaSach = QtWidgets.QPushButton(parent=self.groupBoxCo)
        self.pushButtonXoaSach.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 2px solid #0077b6; \n"
"    border-radius: 8px; \n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu xám nhạt khi hover */\n"
"    border: 2px solid #005f8a; /* Viền đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Màu nhấn */\n"
"    border: 2px solid #004a6d; \n"
"}\n"
"")
        self.pushButtonXoaSach.setIcon(icon)
        self.pushButtonXoaSach.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonXoaSach.setObjectName("pushButtonXoaSach")
        self.gridLayout_2.addWidget(self.pushButtonXoaSach, 0, 2, 1, 1)
        self.pushButton_Signout = QtWidgets.QPushButton(parent=self.groupBoxCo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Signout.sizePolicy().hasHeightForWidth())
        self.pushButton_Signout.setSizePolicy(sizePolicy)
        self.pushButton_Signout.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_Signout.setMaximumSize(QtCore.QSize(68, 68))
        self.pushButton_Signout.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 2px solid #0077b6; \n"
"    border-radius: 5px; \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu xám nhạt khi hover */\n"
"    border: 2px solid #005f8a; /* Viền đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Màu nhấn */\n"
"    border: 2px solid #004a6d; \n"
"}\n"
"")
        self.pushButton_Signout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../images/ic_signout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Signout.setIcon(icon1)
        self.pushButton_Signout.setIconSize(QtCore.QSize(68, 68))
        self.pushButton_Signout.setCheckable(False)
        self.pushButton_Signout.setAutoExclusive(True)
        self.pushButton_Signout.setObjectName("pushButton_Signout")
        self.gridLayout_2.addWidget(self.pushButton_Signout, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBoxCo)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1574, 26))
        self.menubar.setObjectName("menubar")
        self.menuSystem = QtWidgets.QMenu(parent=self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        self.menuExportData = QtWidgets.QMenu(parent=self.menuSystem)
        self.menuExportData.setObjectName("menuExportData")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../../.designer/ProductManagement/Images/ic_exit_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionCsv_File = QtGui.QAction(parent=MainWindow)
        self.actionCsv_File.setObjectName("actionCsv_File")
        self.actionTxt_File = QtGui.QAction(parent=MainWindow)
        self.actionTxt_File.setObjectName("actionTxt_File")
        self.actionXML_File = QtGui.QAction(parent=MainWindow)
        self.actionXML_File.setObjectName("actionXML_File")
        self.actionJSON_File = QtGui.QAction(parent=MainWindow)
        self.actionJSON_File.setObjectName("actionJSON_File")
        self.actionExcel_File_Import = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../../.designer/ProductManagement/Images/ic_excel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExcel_File_Import.setIcon(icon3)
        self.actionExcel_File_Import.setObjectName("actionExcel_File_Import")
        self.actionPickle_File = QtGui.QAction(parent=MainWindow)
        self.actionPickle_File.setObjectName("actionPickle_File")
        self.actionTxt_FIle = QtGui.QAction(parent=MainWindow)
        self.actionTxt_FIle.setObjectName("actionTxt_FIle")
        self.actionCsv_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionCsv_File_2.setObjectName("actionCsv_File_2")
        self.actionJSON_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionJSON_File_2.setObjectName("actionJSON_File_2")
        self.actionExcel_File_Export = QtGui.QAction(parent=MainWindow)
        self.actionExcel_File_Export.setIcon(icon3)
        self.actionExcel_File_Export.setShortcut("")
        self.actionExcel_File_Export.setObjectName("actionExcel_File_Export")
        self.actionPickle_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionPickle_File_2.setObjectName("actionPickle_File_2")
        self.actionXML_File_2 = QtGui.QAction(parent=MainWindow)
        self.actionXML_File_2.setObjectName("actionXML_File_2")
        self.actionHelp = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../ProductManagement/Images/IC_help.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionHelp.setIcon(icon4)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../ProductManagement/Images/IC_about.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName("actionAbout")
        self.menuExportData.addAction(self.actionExcel_File_Export)
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.menuExportData.menuAction())
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSystem.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ngô Hoàng Khải"))
        self.label.setText(_translate("MainWindow", "Quản lý Sách"))
        self.groupBoxCo.setTitle(_translate("MainWindow", "Book List:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pub Year"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quantity"))
        self.label_2.setText(_translate("MainWindow", "ISBN:"))
        self.label_3.setText(_translate("MainWindow", "Book Name:"))
        self.label_6.setText(_translate("MainWindow", "Quantity:"))
        self.label_5.setText(_translate("MainWindow", "Pub Year:"))
        self.label_4.setText(_translate("MainWindow", "Author:"))
        self.pushButtonThemSach.setText(_translate("MainWindow", "Add book"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Update"))
        self.pushButtonXoaSach.setText(_translate("MainWindow", "Delete book"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.menuExportData.setTitle(_translate("MainWindow", "ExportData"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))
        self.actionCsv_File.setText(_translate("MainWindow", "Csv File"))
        self.actionTxt_File.setText(_translate("MainWindow", "Txt File"))
        self.actionXML_File.setText(_translate("MainWindow", "XML File"))
        self.actionJSON_File.setText(_translate("MainWindow", "JSON File"))
        self.actionExcel_File_Import.setText(_translate("MainWindow", "Excel File"))
        self.actionExcel_File_Import.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionPickle_File.setText(_translate("MainWindow", "Pickle File"))
        self.actionTxt_FIle.setText(_translate("MainWindow", "Txt FIle"))
        self.actionCsv_File_2.setText(_translate("MainWindow", "Csv File"))
        self.actionJSON_File_2.setText(_translate("MainWindow", "JSON File"))
        self.actionExcel_File_Export.setText(_translate("MainWindow", "Excel File"))
        self.actionPickle_File_2.setText(_translate("MainWindow", "Pickle File"))
        self.actionXML_File_2.setText(_translate("MainWindow", "XML File"))
        self.actionHelp.setText(_translate("MainWindow", "Current Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
