# Form implementation generated from reading ui file 'D:\duanmonhoc\ui\QuanliMuonSach.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 848)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_UI = QtWidgets.QGridLayout()
        self.gridLayout_UI.setObjectName("gridLayout_UI")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 270))
        self.groupBox.setStyleSheet("color: rgb(0, 51, 102);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(245, 245, 245);")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: white;  /* Nền trắng */\n"
"    border: 2px solid #0078D7;  /* Viền xanh đậm */\n"
"    border-radius: 5px;  /* Bo góc */\n"
"    padding: 5px;  /* Khoảng cách bên trong */\n"
"    font-size: 16px;  /* Cỡ chữ to hơn */\n"
"    color: black;  /* Màu chữ đen */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    background-color: white;  /* Nền dropdown */\n"
"    width: 25px;  /* Tăng kích thước khu vực dropdown */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down-arrow.png);  /* Đổi icon mũi tên nếu cần */\n"
"    width: 16px;  /* Tăng kích thước mũi tên */\n"
"    height: 16px;\n"
"    margin-right: 5px;  /* Khoảng cách với viền phải */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: white;\n"
"    selection-background-color: #0078D7;  /* Màu nền khi chọn */\n"
"    selection-color: white;  /* Chữ trắng khi chọn */\n"
"    border-radius: 5px;\n"
"    font-size: 16px;  /* Cỡ chữ trong danh sách */\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 0, 1, 1, 1)
        self.lineEdit_Infor = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_Infor.setStyleSheet("background-color: rgb(255, 255, 255); border-radius: 5px;border: 1px solid black; padding: 3px")
        self.lineEdit_Infor.setObjectName("lineEdit_Infor")
        self.gridLayout_4.addWidget(self.lineEdit_Infor, 1, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonLoc = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonLoc.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 2px solid #0077b6; \n"
"    border-radius: 8px; \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu xám nhạt khi hover */\n"
"    border: 2px solid #005f8a; /* Viền đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Màu nhấn */\n"
"    border: 2px solid #004a6d; \n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../images/ic_Filter.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLoc.setIcon(icon)
        self.pushButtonLoc.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonLoc.setObjectName("pushButtonLoc")
        self.gridLayout_2.addWidget(self.pushButtonLoc, 0, 2, 1, 1)
        self.pushButtonTra = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonTra.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 2px solid #0077b6; \n"
"    border-radius: 8px; \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu xám nhạt khi hover */\n"
"    border: 2px solid #005f8a; /* Viền đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Màu nhấn */\n"
"    border: 2px solid #004a6d; \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../images/icon_giveback.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTra.setIcon(icon1)
        self.pushButtonTra.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonTra.setObjectName("pushButtonTra")
        self.gridLayout_2.addWidget(self.pushButtonTra, 0, 1, 1, 1)
        self.pushButtonMuon = QtWidgets.QPushButton(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMuon.sizePolicy().hasHeightForWidth())
        self.pushButtonMuon.setSizePolicy(sizePolicy)
        self.pushButtonMuon.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 2px solid #0077b6; \n"
"    border-radius: 8px; \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu xám nhạt khi hover */\n"
"    border: 2px solid #005f8a; /* Viền đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Màu nhấn */\n"
"    border: 2px solid #004a6d; \n"
"}\n"
"")
        self.pushButtonMuon.setObjectName("pushButtonMuon")
        self.gridLayout_2.addWidget(self.pushButtonMuon, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_UI.addWidget(self.groupBox, 9, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_UI.addItem(spacerItem, 1, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(40, 53, 146))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(40, 53, 146))
        brush = QtGui.QBrush(QtGui.QColor(40, 53, 146))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(40, 53, 146))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(40, 53, 146))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(40, 53, 146))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(40, 53, 146))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(40, 53, 146))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(110)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(80)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_UI.addWidget(self.tableWidget, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_UI.addItem(spacerItem1, 8, 0, 1, 1)
        self.label_welcomeuser = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_welcomeuser.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"color: rgb(0, 51, 102);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_welcomeuser.setObjectName("label_welcomeuser")
        self.gridLayout_UI.addWidget(self.label_welcomeuser, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"color: rgb(0, 51, 102);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidgetsachmuon = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.tableWidgetsachmuon.setStyleSheet("background-color: rgb(40,103,129);")
        self.tableWidgetsachmuon.setObjectName("tableWidgetsachmuon")
        self.tableWidgetsachmuon.setColumnCount(5)
        self.tableWidgetsachmuon.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetsachmuon.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetsachmuon.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetsachmuon.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidgetsachmuon.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetsachmuon.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetsachmuon.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetsachmuon.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetsachmuon.setHorizontalHeaderItem(4, item)
        self.tableWidgetsachmuon.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidgetsachmuon.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidgetsachmuon.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetsachmuon.verticalHeader().setDefaultSectionSize(70)
        self.verticalLayout.addWidget(self.tableWidgetsachmuon)
        self.gridLayout_UI.addWidget(self.groupBox_2, 7, 3, 4, 1)
        self.gridLayout.addLayout(self.gridLayout_UI, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pushButton_Chatbot = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Chatbot.sizePolicy().hasHeightForWidth())
        self.pushButton_Chatbot.setSizePolicy(sizePolicy)
        self.pushButton_Chatbot.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_Chatbot.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 2px solid #0077b6; \n"
"    border-radius: 5px; \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu xám nhạt khi hover */\n"
"    border: 2px solid #005f8a; /* Viền đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Màu nhấn */\n"
"    border: 2px solid #004a6d; \n"
"}\n"
"")
        self.pushButton_Chatbot.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../images/ic_chatbot.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Chatbot.setIcon(icon2)
        self.pushButton_Chatbot.setIconSize(QtCore.QSize(68, 68))
        self.pushButton_Chatbot.setCheckable(False)
        self.pushButton_Chatbot.setAutoRepeat(True)
        self.pushButton_Chatbot.setAutoExclusive(True)
        self.pushButton_Chatbot.setObjectName("pushButton_Chatbot")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pushButton_Chatbot)
        self.pushButton_Signout = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Signout.sizePolicy().hasHeightForWidth())
        self.pushButton_Signout.setSizePolicy(sizePolicy)
        self.pushButton_Signout.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_Signout.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 2px solid #0077b6; \n"
"    border-radius: 5px; \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu xám nhạt khi hover */\n"
"    border: 2px solid #005f8a; /* Viền đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Màu nhấn */\n"
"    border: 2px solid #004a6d; \n"
"}\n"
"")
        self.pushButton_Signout.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\duanmonhoc\\ui\\../images/ic_signout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Signout.setIcon(icon3)
        self.pushButton_Signout.setIconSize(QtCore.QSize(68, 68))
        self.pushButton_Signout.setCheckable(False)
        self.pushButton_Signout.setAutoExclusive(True)
        self.pushButton_Signout.setObjectName("pushButton_Signout")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pushButton_Signout)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Các chức năng mượn sách"))
        self.label.setText(_translate("MainWindow", "Category:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ISBN"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Publication Year"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Author"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Quantity"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Book Name"))
        self.lineEdit_Infor.setPlaceholderText(_translate("MainWindow", "Your finding information..."))
        self.pushButtonLoc.setText(_translate("MainWindow", "Find"))
        self.pushButtonTra.setText(_translate("MainWindow", "Give Back"))
        self.pushButtonMuon.setText(_translate("MainWindow", "Borrow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pub Year"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quantity"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Test"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_welcomeuser.setText(_translate("MainWindow", "Xin chào"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Các cuốn sách đang mượn:"))
        item = self.tableWidgetsachmuon.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetsachmuon.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetsachmuon.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetsachmuon.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.tableWidgetsachmuon.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Name"))
        item = self.tableWidgetsachmuon.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author"))
        item = self.tableWidgetsachmuon.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pub Year"))
        item = self.tableWidgetsachmuon.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quantity"))
